# DEVELOPMENT
version: '3'
services:
  db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  api:
    build:
     context: ./
     dockerfile: ./apps/api/Dockerfile
    depends_on:
      - db
    ports:
      - '3001:3001'
    restart: always
    env_file:
      - ./apps/api/.env.staging.local
    environment:
      NODE_ENV: staging
  web:
    build:
     context: ./
     dockerfile: ./apps/web/Dockerfile
    depends_on:
      - api
    ports:
      - '80:3000'
    restart: always
    env_file:
      - ./apps/web/.env.staging.local
    environment:
      NODE_ENV: staging
